aston_back_homepage:
    path:     /
    defaults: { _controller: AstonBackBundle:Default:index }
    
aston_back_blog_add:
    path: /blog/add
    defaults: {_controller: AstonBackBundle:Post:add }
    methods: [GET,POST]
    
aston_back_blog_list:
    path: /blog
    defaults: {_controller: AstonBackBundle:Post:list }    
    
aston_back_blog_update:
    path: /blog/post/update/{id}
    defaults: {_controller: AstonBackBundle:Post:update }        
    methods: [GET,POST]
    requirements:
        id: \d+
        
aston_back_blog_delete:
    path: /blog/post/delete/{id}
    defaults: {_controller: AstonBackBundle:Post:delete }  
    methods: [GET,POST]
    requirements:
        id: \d+
        
    
        
aston_back_categorie_list:
    path: /blog/categorie
    defaults: {_controller: AstonBackBundle:Categorie:list }
    methods: [GET,POST]  
    
aston_back_categorie_add:
    path: /blog/categorie/add
    defaults: {_controller: AstonBackBundle:Categorie:add }
    methods: [GET,POST]  
    
aston_back_categorie_update:
    path: /blog/categorie/update/{id}
    defaults: {_controller: AstonBackBundle:Categorie:update }        
    methods: [GET,POST]
    requirements:
        id: \d+
        
aston_back_categorie_delete:
    path: /blog/categorie/delete/{id}
    defaults: {_controller: AstonBackBundle:Categorie:delete }  
    methods: [GET,POST]
    requirements:
        id: \d+    
    