fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

aston_back:
    resource: "@AstonBackBundle/Resources/config/routing.yml"
    prefix:   /admin

aston_front:
    resource: "@AstonFrontBundle/Resources/config/routing.yml"
    prefix:   /
    

