<?php

namespace Aston\BackBundle\Repository;
use Aston\BackBundle\Entity\User;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * DQL: doctrine query language
     * @param User $user
     */
    public function findPosts(User $user){
        $qb=$this->createQueryBuilder('p');
        $whereStmt = $qb->expr()->eq('p.user',':user');
        
        return $qb->where($whereStmt)
                  ->setParameter('user', $user)
                  ->getQuery()
                  ->execute();
    }
}
