aston_front_homepage:
    path:     /
    defaults: { _controller: AstonFrontBundle:Default:index }

aston_front_hello:
    path:     /hello/{name}
    defaults: { _controller: AstonFrontBundle:Default:hello, name: "toto"}
    methods: [GET,POST]
    requirements:
        name: "[a-z]+"
        
aston_front_about:
    path:     /about
    defaults: { _controller: AstonFrontBundle:Default:about}
    methods: [GET,POST]
         
aston_front_post:
    path:     /blog
    defaults: { _controller: AstonFrontBundle:Default:post}
    methods: [GET,POST]

aston_front_contact:
    path:     /contact
    defaults: { _controller: AstonFrontBundle:Default:contact}
    methods: [GET,POST]
    
aston_front_sesswrite:
    path:     /sess/write
    defaults: { _controller: AstonFrontBundle:Default:sessionWrite}
    methods: [GET,POST]
        
aston_front_sessread:
    path:     /sess/read/{name}
    defaults: { _controller: AstonFrontBundle:Default:sessionRead}
    methods: [GET,POST]        
        
             